apiVersion: v1
kind: Secret
metadata:
  name: clusternet-agent-cluster-registration
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  parentURL: {{ .Values.parentURL }}
  regToken: {{ .Values.registrationToken }}
